'use strict';

(function () {
  window.designData = {
    images: [
      'img/content/berries-mobile@1x.jpg',
      'img/content/marshmallow-mobile@1x.jpg',
      'img/content/berries2-mobile@1x.jpg',
      'img/content/berries3-mobile@1x.jpg',
      'img/content/birch-mobile@1x.jpg',
      'img/content/flowers2-mobile@1x.jpg',
      'img/content/flowers3-mobile@1x.jpg',
      'img/content/flowers-mobile@1x.jpg',
      'img/content/kids-mobile@1x.jpg',
      'img/content/offer-mobile@1x.jpg',
      'img/content/pink-mobile@1x.jpg',
      'img/content/romantic-mobile@1x.jpg',
      'img/content/shoco-berry-mobile@1x.jpg',
      'img/content/transformer-mobile@1x.jpg',
      'img/content/wedding2-mobile@1x.jpg'
    ],
    alt: [
      'Изображение оформления «Ягодное ассорти»',
      'Изображение оформления «Маршмэллоу»',
      'Изображение оформления «Ягодный без мастики»',
      'Изображение оформления «Рустик»',
      'Изображение оформления «Берёзка»',
      'Изображение оформления «Цветочная композиция»',
      'Изображение оформления «Цветочный без мастики»',
      'Изображение оформления «Розы с вишнями»',
      'Изображение оформления «Детское рождество»',
      'Изображение оформления «Предложение»',
      'Изображение оформления «Розовая принцесса»',
      'Изображение оформления «Романтика»',
      'Изображение оформления «Клубника в шоколаде»',
      'Изображение оформления «Бамблби»',
      'Изображение оформления «Свадебная классика»'
    ],
    headings: [
      'Ягодное ассорти',
      '«Маршмэллоу»',
      'Ягодный без мастики',
      '«Рустик»',
      '«Берёзка»',
      '«Цветочная композиция»',
      'Цветочный без мастики',
      'Розы с вишнями',
      '«Детское рождество»',
      '«Предложение»',
      '«Розовая принцесса»',
      '«Романтика»',
      'Клубника в шоколаде',
      '«Бамблби»',
      '«Свадебная классика»'
    ],
    prices: [
      '700 руб/кг',
      '600 руб/кг',
      '550 руб/кг',
      '650 руб/кг',
      '800 руб/кг',
      '750 руб/кг',
      '700 руб/кг',
      '800 руб/кг',
      '900 руб/кг',
      '650 руб/кг',
      '750 руб/кг',
      '1050 руб/кг',
      '950 руб/кг',
      '900 руб/кг',
      '950 руб/кг'
    ],
    inputsValues: [
      'berry-allsorts',
      'marshmallow',
      'berries-no-mastic',
      'rustic',
      'birch',
      'flower-bed',
      'flowers-no-mastic',
      'cherry-rose',
      'kids-christmas',
      'offer',
      'opink-princess',
      'romantic',
      'shoko-strawberry',
      'bumblebee',
      'wedding-classic'
    ]
  };
})();
